AllCops:
  TargetRubyVersion: 2.4

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'pyr.gemspec'
    - 'spec/**/*'
    - 'Rakefile'

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'
