language: ruby

rvm:
  - 2.3.0
  - 2.3.4
  - 2.4.1
  - jruby-9.1.6.0
  - jruby-head
  - rbx-3
  - ruby-head

sudo: false

cache: bundler

bundler_args: --without development --retry=3 --jobs=3

before_install:
  - gem update --system
  - gem update bundler

env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-3
    - rvm: ruby-head
  fast_finish: true

notifications:
  email:
    on_success: never
    on_failure: always
